MAP_COLS = 21;
MAP_ROWS = 21;
MAP_DEFAULT = 16;

CENTER_BLOCK_COL_LEFT = Math.ceil((MAP_COLS - MAP_DEFAULT) / 2);
CENTER_BLOCK_COL_RIGHT = CENTER_BLOCK_COL_LEFT + MAP_DEFAULT;
CENTER_BLOCK_ROW_TOP = Math.floor((MAP_ROWS - MAP_DEFAULT) / 2);
CENTER_BLOCK_ROW_BOTTOM = CENTER_BLOCK_ROW_TOP + MAP_DEFAULT;

CELL_COLOR_WRITE = "004D00";
CELL_COLOR_BLANK = "FFFFFF";
CELL_COLOR_DEFAULT = "88DD88";

MODE_NAME = [
    "円",
    "四角形",
    "自由描画"
];

var writeModeId = 0;
var mapArray = [];
var mapArrayHistory = [];
var blockNum = 0;
var blockNumHistory = [];