MAP_COLS = 101;
MAP_ROWS = 101;
MAP_COLS_MAX = 201;
MAP_ROWS_MAX = 201;
MAP_DEFAULT = 16;

BLOCK_NUM_MAX = 15000;

CENTER_BLOCK_COL_LEFT = Math.ceil((MAP_COLS_MAX - MAP_DEFAULT) / 2);
CENTER_BLOCK_COL_RIGHT = CENTER_BLOCK_COL_LEFT + MAP_DEFAULT;
CENTER_BLOCK_ROW_TOP = Math.floor((MAP_ROWS_MAX - MAP_DEFAULT) / 2);
CENTER_BLOCK_ROW_BOTTOM = CENTER_BLOCK_ROW_TOP + MAP_DEFAULT;

CELL_COLOR_WRITE = "004D00";
CELL_COLOR_BLANK = "FFFFFF";
CELL_COLOR_DEFAULT = "88DD88";

MODE_NAME = [
    "円",
    "四角形",
    "塗りつぶし",
    "自由描画"
];
MODE_ELLIPSE = 0;
MODE_RECTANGLE = 1;
MODE_RANGE = 2;
MODE_FREE = 3;

var writeModeId = 3;
var mapArray = [];
var mapArrayHistory = [];
var blockNum = 0;
var blockNumHistory = [];

var mapOffsetRow = 0;
var mapOffsetCol = 0;
